version: '3'

networks:
  petclinic:
    driver: bridge

volumes:
  myapp:

services:
  mysqldb:
    image: mysql:8.0
    restart: always
    networks:
      - aulaDockerPri
    environment:
      - MYSQL_ROOT_PASSWORD=testePri
      - MYSQL_DATABASE=aulaDockerPri
      - MYSQL_TCP_PORT=3306

  app:
    build: .
    restart: always
    networks:
      - aulaDockerPri
    ports:
      - 8080:8080
    volumes:
      - myapp:/home
    depends_on:
      - mysqldb