version: '3'

services:
  mysqldb:
    image: mysql:8.0
    container_name: db_mysql_pri
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER='root'
    volumes:
      - ./data:/var/lib/mysql